services:
  next-app:
    image: ${NEXT_COMPOSE_IMAGE:-sendapp/next-app-dev:latest}
    restart: always
    ports:
      - 3000:3000
    env_file:
      - path: .env.local
        required: false
      - path: .env.local.docker
        required: false
      - path: .env
        required: false
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - supabase_network_send
secrets:
  SUPABASE_DB_URL:
    environment: SUPABASE_DB_URL
  SUPABASE_SERVICE_ROLE:
    environment: SUPABASE_SERVICE_ROLE
  TURBO_TOKEN:
    environment: TURBO_TOKEN
  TURBO_TEAM:
    environment: TURBO_TEAM

networks:
  supabase_network_send:
    driver: bridge
