services:
  next-app:
    image: 0xsend/sendapp/next-app:latest
    build:
      context: .
      dockerfile: ./apps/next/Dockerfile
      tags:
        - 0xsend/sendapp/next-app:${GIT_HASH:-latest}
        - 0xsend/sendapp/next-app:latest
      secrets:
        - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
        - NEXT_PUBLIC_SUPABASE_URL
        - SUPABASE_SERVICE_ROLE
        - NEXT_PUBLIC_SUPABASE_ANON_KEY
    restart: always
    ports:
      - 3000:3000
    environment:
      CI: ${CI:-}
    env_file:
      - path: .env.local
        required: false
      - path: .env.development.docker
secrets:
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:
    environment: NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
  NEXT_PUBLIC_SUPABASE_URL:
    environment: NEXT_PUBLIC_SUPABASE_URL
  SUPABASE_SERVICE_ROLE:
    environment: SUPABASE_SERVICE_ROLE
  NEXT_PUBLIC_SUPABASE_ANON_KEY:
    environment: NEXT_PUBLIC_SUPABASE_ANON_KEY
