services:
  next-app:
    image: ${NEXT_APP_IMAGE_TAG:-sendapp/next-app-dev:latest}
    build:
      context: .
      dockerfile: ./apps/next/Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_PROJECT_ID=${NEXT_PUBLIC_SUPABASE_PROJECT_ID}
        - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_GRAPHQL_URL=${NEXT_PUBLIC_SUPABASE_GRAPHQL_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_MAINNET_RPC_URL=${NEXT_PUBLIC_MAINNET_RPC_URL}
        - NEXT_PUBLIC_BASE_RPC_URL=${NEXT_PUBLIC_BASE_RPC_URL}
        - NEXT_PUBLIC_BUNDLER_RPC_URL=${NEXT_PUBLIC_BUNDLER_RPC_URL}
        - NEXT_PUBLIC_MAINNET_CHAIN_ID=${NEXT_PUBLIC_MAINNET_CHAIN_ID}
        - NEXT_PUBLIC_BASE_CHAIN_ID=${NEXT_PUBLIC_BASE_CHAIN_ID}
        - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
        - NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
        - NEXT_PUBLIC_CDP_APP_ID=${NEXT_PUBLIC_CDP_APP_ID}
        - NEXT_PUBLIC_ONCHAINKIT_API_KEY=${NEXT_PUBLIC_ONCHAINKIT_API_KEY}
        - NEXT_PUBLIC_KYBER_SWAP_BASE_URL=${NEXT_PUBLIC_KYBER_SWAP_BASE_URL}
        - NEXT_PUBLIC_KYBER_CLIENT_ID=${NEXT_PUBLIC_KYBER_CLIENT_ID}
    deploy:
      resources:
        limits:
          memory: 4G # Set maximum memory limit
          cpus: '2' # Limit to 2 CPUs
        reservations:
          memory: 2G # Guarantee this amount of memory
          cpus: '1' # Reserve at least 1 CPU
    ports:
      - ${NEXT_APP_PORT:-3000}:3000
    env_file:
      - path: .env.development
      - path: .env.development.docker
      - path: .env.local
        required: false
      - path: .env.local.docker
        required: false
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - supabase_network_send

networks:
  supabase_network_send:
    external: true
