services:
  # Dockerizing the Next app does not make much sense yet since it requires pre-rendering and we don't have a good way to do that yet
  next-app:
    image: ${NEXT_APP_IMAGE_TAG:-sendapp/next-app-dev:latest}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PACKAGE=next-app
        - NEXT_PUBLIC_SUPABASE_PROJECT_ID=${NEXT_PUBLIC_SUPABASE_PROJECT_ID}
        - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_GRAPHQL_URL=${NEXT_PUBLIC_SUPABASE_GRAPHQL_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_MAINNET_RPC_URL=${NEXT_PUBLIC_MAINNET_RPC_URL}
        - NEXT_PUBLIC_BASE_RPC_URL=${NEXT_PUBLIC_BASE_RPC_URL}
        - NEXT_PUBLIC_BUNDLER_RPC_URL=${NEXT_PUBLIC_BUNDLER_RPC_URL}
        - NEXT_PUBLIC_MAINNET_CHAIN_ID=${NEXT_PUBLIC_MAINNET_CHAIN_ID}
        - NEXT_PUBLIC_BASE_CHAIN_ID=${NEXT_PUBLIC_BASE_CHAIN_ID}
        - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
        - NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
        - NEXT_PUBLIC_CDP_APP_ID=${NEXT_PUBLIC_CDP_APP_ID}
        - NEXT_PUBLIC_ONCHAINKIT_API_KEY=${NEXT_PUBLIC_ONCHAINKIT_API_KEY}
        - NEXT_PUBLIC_KYBER_SWAP_BASE_URL=${NEXT_PUBLIC_KYBER_SWAP_BASE_URL}
        - NEXT_PUBLIC_KYBER_CLIENT_ID=${NEXT_PUBLIC_KYBER_CLIENT_ID}
    ports:
      - ${NEXT_APP_PORT:-3000}:3000
    env_file:
      - path: .env.development
      - path: .env.development.docker
      - path: .env.local
        required: false
      - path: .env.local.docker
        required: false
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - supabase_network_send

  # Distributor
  distributor:
    image: ${DISTRIBUTOR_IMAGE_TAG:-sendapp/distributor-dev:latest}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PACKAGE=distributor
    env_file:
      - path: .env.development
      - path: .env.development.docker
      - path: .env.local
        required: false
      - path: .env.local.docker
        required: false
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - supabase_network_send

networks:
  supabase_network_send:
    external: true
