services:
  next-app:
    image: 0xsend/sendapp/next-app:latest
    build:
      context: .
      dockerfile: ./apps/next/Dockerfile
      tags:
        - 0xsend/sendapp/next-app:${GIT_HASH:-latest}
        - 0xsend/sendapp/next-app:latest
      secrets:
        - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
        - NEXT_PUBLIC_SUPABASE_URL
        - NEXT_PUBLIC_SUPABASE_GRAPHQL_URL
        - NEXT_PUBLIC_MAINNET_RPC_URL
        - NEXT_PUBLIC_BASE_RPC_URL
        - NEXT_PUBLIC_BUNDLER_RPC_URL
        - SUPABASE_DB_URL
        - SUPABASE_SERVICE_ROLE
        - NEXT_PUBLIC_SUPABASE_ANON_KEY
    restart: always
    ports:
      - 3000:3000
    env_file:
      - path: .env.local
        required: false
      - path: .env.development.docker
      - path: .env.local.docker
        required: false
    secrets:
      - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
      - NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_GRAPHQL_URL
      - NEXT_PUBLIC_MAINNET_RPC_URL
      - NEXT_PUBLIC_BASE_RPC_URL
      - NEXT_PUBLIC_BUNDLER_RPC_URL
      - SUPABASE_DB_URL
      - SUPABASE_SERVICE_ROLE
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
secrets:
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:
    file: ./var/NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID.txt
  NEXT_PUBLIC_SUPABASE_URL:
    file: ./var/NEXT_PUBLIC_SUPABASE_URL.txt
  NEXT_PUBLIC_SUPABASE_GRAPHQL_URL:
    file: ./var/NEXT_PUBLIC_SUPABASE_GRAPHQL_URL.txt
  NEXT_PUBLIC_MAINNET_RPC_URL:
    file: ./var/NEXT_PUBLIC_MAINNET_RPC_URL.txt
  NEXT_PUBLIC_BASE_RPC_URL:
    file: ./var/NEXT_PUBLIC_BASE_RPC_URL.txt
  NEXT_PUBLIC_BUNDLER_RPC_URL:
    file: ./var/NEXT_PUBLIC_BUNDLER_RPC_URL.txt
  SUPABASE_DB_URL:
    file: ./var/SUPABASE_DB_URL.txt
  SUPABASE_SERVICE_ROLE:
    file: ./var/SUPABASE_SERVICE_ROLE.txt
  NEXT_PUBLIC_SUPABASE_ANON_KEY:
    file: ./var/NEXT_PUBLIC_SUPABASE_ANON_KEY.txt
