services:
  next-app:
    image: 0xsend/sendapp/next-app:latest
    build:
      context: .
      dockerfile: ./apps/next/Dockerfile
      tags:
        - 0xsend/sendapp/next-app:${GIT_HASH:-latest}
        - 0xsend/sendapp/next-app:latest
      args:
        - CI=${CI:-}
        - DEBUG=${DEBUG:-}
        - NEXT_PUBLIC_SUPABASE_PROJECT_ID=${NEXT_PUBLIC_SUPABASE_PROJECT_ID}
        - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_GRAPHQL_URL=${NEXT_PUBLIC_SUPABASE_GRAPHQL_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_MAINNET_RPC_URL=${NEXT_PUBLIC_MAINNET_RPC_URL}
        - NEXT_PUBLIC_BASE_RPC_URL=${NEXT_PUBLIC_BASE_RPC_URL}
        - NEXT_PUBLIC_BUNDLER_RPC_URL=${NEXT_PUBLIC_BUNDLER_RPC_URL}
        - NEXT_PUBLIC_MAINNET_CHAIN_ID=${NEXT_PUBLIC_MAINNET_CHAIN_ID}
        - NEXT_PUBLIC_BASE_CHAIN_ID=${NEXT_PUBLIC_BASE_CHAIN_ID}
        - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
      secrets:
        - SUPABASE_DB_URL
        - SUPABASE_SERVICE_ROLE
    restart: always
    ports:
      - 3000:3000
    env_file:
      - path: .env.local
        required: false
      - path: .env.development
      - path: .env.development.docker
      - path: .env.local.docker
        required: false
    secrets:
      - SUPABASE_DB_URL
      - SUPABASE_SERVICE_ROLE
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - supabase_network_send
secrets:
  SUPABASE_DB_URL:
    file: ./var/SUPABASE_DB_URL.txt
  SUPABASE_SERVICE_ROLE:
    file: ./var/SUPABASE_SERVICE_ROLE.txt

networks:
  supabase_network_send:
    external: true
