name: Deploy
description: "Deploy the project to Vercel and Supabase."
inputs:
  vercel-token:
    description: "The Vercel token to use for deployment."
    required: true
  vercel-org-id:
    description: "The Vercel organization ID to use for deployment."
    required: true
  vercel-project-id:
    description: "The Vercel project ID to use for deployment."
    required: true
  production:
    description: "Whether to deploy to the production environment."
    required: false
    default: "false"
  supabase-project-id:
    description: "The Supabase project ID to use for deployment."
    required: true
  supabase-access-token:
    description: "The Supabase access token to use for deployment."
    required: true
  supabase-db-password:
    description: "The Supabase database password to use for deployment."
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        yarn-install: false
      env:
        YARN_ENABLE_HARDENED_MODE: "0"
    - name: Supabase Deploy
      id: deploy
      uses: ./.github/actions/supabase-deploy
      with:
        supabase-project-id: ${{ inputs.supabase-project-id }}
        supabase-access-token: ${{ inputs.supabase-access-token }}
        supabase-db-password: ${{ inputs.supabase-db-password }}
    - name: Extract Branch
      id: extract-branch
      uses: ./.github/actions/extract-branch
    - name: Public Hostname
      shell: bash
      id: public-hostname
      run: echo "public-hostname=sendapp-${{steps.extract-branch.outputs.branch}}-0xsend.vercel.app" >> $GITHUB_OUTPUT
    - name: Vercel Deploy
      uses: ./.github/actions/vercel-deploy
      with:
        vercel-token: ${{ inputs.vercel-token }}
        vercel-org-id: ${{ inputs.vercel-org-id }}
        vercel-project-id: ${{ inputs.vercel-project-id }}
        public-hostname: ${{ steps.public-hostname.outputs.public-hostname }}
        production: ${{ inputs.production }}
      env:
        YARN_ENABLE_HARDENED_MODE: "0"
