name: "Setup Environment"
description: "Set up Node.js, install Foundry, and set up Bun. Runs Yarn install."
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: "yarn"
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    - name: Yarn Install
      run: yarn install --immutable
