name: Supabase Schema Drift Check
description: "Check for schema drift by comparing database with declarative schemas"
runs:
  using: "composite"
  steps:
    - uses: supabase/setup-cli@v1
      with:
        version: latest
    - name: Check for Schema Drift
      shell: bash
      working-directory: ./supabase
      run: supabase db diff -f changes
    - name: Ensure Declarative Schema is Up to Date
      shell: bash
      run: git diff --exit-code
