name: Supabase Schema Drift Check
description: "Check for schema drift by comparing database with declarative schemas"
runs:
  using: "composite"
  steps:
    - uses: supabase/setup-cli@v1
      with:
        version: latest
    - name: Start Supabase Local Instance
      shell: bash
      run: |
        # Start Supabase local instance
        supabase start --ignore-health-check

        # Wait for database to be ready
        echo "Waiting for database to be ready..."
        timeout=60
        count=0
        while [ $count -lt $timeout ]; do
          if supabase status | grep -q "API URL.*http://127.0.0.1:54321"; then
            echo "Database is ready!"
            break
          fi
          echo "Waiting... ($count/$timeout)"
          sleep 2
          count=$((count + 2))
        done

        if [ $count -ge $timeout ]; then
          echo "Timeout waiting for database to start"
          supabase status
          exit 1
        fi
    - name: Check for Schema Drift
      shell: bash
      working-directory: ./supabase
      env:
        PGSSLMODE: disable
      run: supabase db diff -f changes
    - name: Ensure Declarative Schema is Up to Date
      shell: bash
      run: |
        # Check for modified files
        git diff --exit-code
        # Check for untracked files in supabase/migrations
        if [ -n "$(git ls-files --others --exclude-standard supabase/migrations/)" ]; then
          echo "Error: Untracked migration files detected in supabase/migrations/"
          git ls-files --others --exclude-standard supabase/migrations/
          exit 1
        fi
