name: "Setup Environment"
description: "Set up Node.js, install Foundry, and set up Bun. Runs Yarn install."
inputs:
  install-foundry:
    description: "Whether to install Foundry."
    required: false
    default: "true"
  install-bun:
    description: "Whether to install Bun."
    required: false
    default: "true"
  install-node:
    description: "Whether to install Node.js."
    required: false
    default: "true"
  yarn-install:
    description: "Whether to run Yarn install."
    required: false
    default: "true"
  build-nextjs:
    description: "Whether to build Next.js."
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      if: ${{ inputs.install-node == 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: "yarn"
    - name: Print a CPU report
      shell: bash
      run: |
        echo "=== CPU report ==="
        lscpu
        echo "=== Memory report ==="
        free -h -t
    - name: Setup Bun
      if: ${{ inputs.install-bun == 'true' }}
      uses: oven-sh/setup-bun@v1
    - name: Install Foundry
      if: ${{ inputs.install-foundry == 'true' }}
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    - name: Yarn Install
      if: ${{ inputs.yarn-install == 'true' }}
      shell: bash
      run: yarn install --immutable  --inline-builds
    - name: Build Next.js
      if: ${{ inputs.build-nextjs == 'true' }}
      shell: bash
      run: |
        cp .env.local.template .env.local
        yarn web:prod
        rm .env.local
    - name: Save Next.js
      if: ${{ inputs.build-nextjs == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-build
        path: ${{ github.workspace }}/apps/next/.next/
        include-hidden-files: true
