name: "Setup Environment"
description: "Set up Node.js, cache Yarn."
inputs:
  yarn-install:
    description: "Whether to run Yarn install."
    required: false
    default: "true"
  build-nextjs:
    description: "Whether to build Next.js."
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      if: ${{ inputs.install-node == 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: "yarn"
    - name: Yarn Install
      if: ${{ inputs.yarn-install == 'true' }}
      shell: bash
      run: yarn install --immutable

    - name: Restore next cache
      uses: actions/cache@v4
      with:
        path: |
          .next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
    - name: Build Next.js
      if: ${{ inputs.build-nextjs == 'true' }}
      shell: bash
      run: |
        cp .env.local.template .env.local
        yarn web:prod
        rm .env.local
    - name: Save Next.js
      if: ${{ inputs.build-nextjs == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-build
        path: ${{ github.workspace }}/apps/next/.next/
