name: "Setup Docker Build Environment"
description: "Build and Push docker image to dockerhub"
inputs:
  build-nextjs-docker:
    description: "Whether to build Next.js docker image"
    required: false
    default: "true"
  push-nextjs-docker-image:
    description: "Whether to push build to dockerhub"
    required: false
    default: "true"
  dockerhub_username:
    description: "Username to login to dockerhub"
    required: false
  dockerhub_password:
    description: "Password to login to dockerhub"
    required: false
runs:
  using: "composite"
  steps:
    - name: Login to dockerhub
      uses: docker/login-action@v3
      if: ${{ inputs.build-nextjs-docker == 'true' }} && ${{ inputs.push-nextjs-docker-image == 'true' }}
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}
    - name: Build and Push image to dockerhub
      shell: bash
      if: ${{ inputs.build-nextjs-docker == 'true' }} && ${{ inputs.push-nextjs-docker-image == 'true' }}
      run: |
        make docker-web-push
        test -f .env.local && rm .env.local
    - name: Cleanup old docker images for sendapp
      run: make docker-clean
