#!/bin/bash
set -e

# Set default values for environment variables
NEXT_PUBLIC_SUPABASE_PROJECT_ID=${NEXT_PUBLIC_SUPABASE_PROJECT_ID:-"dummy-project-id"}
NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL:-"http://localhost:3000"}
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-"https://dummy-project-id.supabase.co"}
NEXT_PUBLIC_SUPABASE_GRAPHQL_URL=${NEXT_PUBLIC_SUPABASE_GRAPHQL_URL:-"https://dummy-project-id.supabase.co/graphql"}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-"dummy-anon-key"}
NEXT_PUBLIC_MAINNET_RPC_URL=${NEXT_PUBLIC_MAINNET_RPC_URL:-"https://ethereum-rpc.example.com"}
NEXT_PUBLIC_BASE_RPC_URL=${NEXT_PUBLIC_BASE_RPC_URL:-"https://base-rpc.example.com"}
NEXT_PUBLIC_BUNDLER_RPC_URL=${NEXT_PUBLIC_BUNDLER_RPC_URL:-"https://bundler-rpc.example.com"}
NEXT_PUBLIC_MAINNET_CHAIN_ID=${NEXT_PUBLIC_MAINNET_CHAIN_ID:-"1"}
NEXT_PUBLIC_BASE_CHAIN_ID=${NEXT_PUBLIC_BASE_CHAIN_ID:-"8453"}
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:-"dummy-walletconnect-id"}
NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY:-"dummy-turnstile-key"}

# Build the Docker image with all required environment variables
docker build \
  --build-arg NEXT_PUBLIC_SUPABASE_PROJECT_ID="$NEXT_PUBLIC_SUPABASE_PROJECT_ID" \
  --build-arg NEXT_PUBLIC_URL="$NEXT_PUBLIC_URL" \
  --build-arg NEXT_PUBLIC_SUPABASE_URL="$NEXT_PUBLIC_SUPABASE_URL" \
  --build-arg NEXT_PUBLIC_SUPABASE_GRAPHQL_URL="$NEXT_PUBLIC_SUPABASE_GRAPHQL_URL" \
  --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY="$NEXT_PUBLIC_SUPABASE_ANON_KEY" \
  --build-arg NEXT_PUBLIC_MAINNET_RPC_URL="$NEXT_PUBLIC_MAINNET_RPC_URL" \
  --build-arg NEXT_PUBLIC_BASE_RPC_URL="$NEXT_PUBLIC_BASE_RPC_URL" \
  --build-arg NEXT_PUBLIC_BUNDLER_RPC_URL="$NEXT_PUBLIC_BUNDLER_RPC_URL" \
  --build-arg NEXT_PUBLIC_MAINNET_CHAIN_ID="$NEXT_PUBLIC_MAINNET_CHAIN_ID" \
  --build-arg NEXT_PUBLIC_BASE_CHAIN_ID="$NEXT_PUBLIC_BASE_CHAIN_ID" \
  --build-arg NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID="$NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID" \
  --build-arg NEXT_PUBLIC_TURNSTILE_SITE_KEY="$NEXT_PUBLIC_TURNSTILE_SITE_KEY" \
  -t sendapp-test \
  -f ./apps/next/Dockerfile \
  .

echo "Docker image build complete!"