name: Deploy to production

on:
  push:
    branches: ['SEND-382']

jobs:
  fingerprint:
    name: Fingerprint
    type: fingerprint
    environment: production

  get_android_build:
    name: Check for existing android build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      profile: production

#  get_ios_build:
#    name: Check for existing ios build
#    needs: [fingerprint]
#    type: get-build
#    params:
#      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
#      profile: production

  build_android:
    name: Build Android
    needs: [get_android_build]
    if: ${{ !needs.get_android_build.outputs.build_id }}
    type: build
    params:
      platform: android
      profile: production

#  build_ios:
#    name: Build iOS
#    needs: [get_ios_build]
#    if: ${{ !needs.get_ios_build.outputs.build_id }}
#    type: build
#    params:
#      platform: ios
#      profile: production

  submit_android_build:
    name: Submit Android Build
    needs: [build_android]
    type: submit 
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}

#  submit_ios_build:
#    name: Submit iOS Build
#    needs: [build_ios]
#    type: submit
#    params:
#      build_id: ${{ needs.build_ios.outputs.build_id }}

  publish_android_update:
    name: Publish Android update
    needs: [get_android_build]
    if: ${{ needs.get_android_build.outputs.build_id }}
    environment: production
    steps:
      - name: Check working directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la

      - name: Install Foundry
        run: |
          # Install Foundry (ignore shell detection errors)
          curl -L https://foundry.paradigm.xyz | bash || true

          # Manually add to PATH for this session
          export PATH="$HOME/.foundry/bin:$PATH"

          # Run foundryup directly from its installed location
          if [ -f "$HOME/.foundry/bin/foundryup" ]; then
            $HOME/.foundry/bin/foundryup
          else
            echo "ERROR: foundryup not found at $HOME/.foundry/bin/foundryup"
            exit 1
          fi

      - name: Install Bun
        run: |
          # Install Bun (ignore shell detection errors)
          curl -fsSL https://bun.sh/install | bash || true

          # Manually add to PATH for this session
          export PATH="$HOME/.bun/bin:$PATH"

          # Verify Bun is installed
          if [ -f "$HOME/.bun/bin/bun" ]; then
            echo "✓ Bun installed successfully"
            $HOME/.bun/bin/bun --version
          else
            echo "ERROR: bun not found at $HOME/.bun/bin/bun"
            exit 1
          fi

      - name: Build monorepo
        run: |
          # Add tools to PATH
          export PATH="$HOME/.foundry/bin:$HOME/.bun/bin:$PATH"

          # Verify tools are available
          echo "Verifying tools..."
          which forge || echo "WARNING: forge not in PATH"
          which bun || echo "WARNING: bun not in PATH"

          # Find monorepo root by looking for package.json with workspaces
          echo "Current directory: $(pwd)"
          echo "Looking for monorepo root..."

          # Start from current directory and search upwards for package.json with workspaces
          MONOREPO_ROOT=$(pwd)
          while [ "$MONOREPO_ROOT" != "/" ]; do
            if [ -f "$MONOREPO_ROOT/package.json" ] && grep -q "workspaces" "$MONOREPO_ROOT/package.json"; then
              echo "Found monorepo root at: $MONOREPO_ROOT"
              break
            fi
            MONOREPO_ROOT=$(dirname "$MONOREPO_ROOT")
          done

          if [ "$MONOREPO_ROOT" = "/" ]; then
            echo "ERROR: Could not find monorepo root (package.json with workspaces)"
            exit 1
          fi

          # Navigate to monorepo root and build
          cd "$MONOREPO_ROOT"
          echo "Building monorepo from $(pwd)..."
          ls -la package.json
          yarn build

      - name: Publish update
        run: |
          # eas update needs to run from the expo app directory
          eas update --branch production --platform android --non-interactive

#  publish_ios_update:
#    name: Publish iOS update
#    needs: [get_ios_build]
#    if: ${{ needs.get_ios_build.outputs.build_id }}
#    environment: production
#    steps:
#      - name: Check working directory
#        run: |
#          echo "Current directory: $(pwd)"
#          echo "Directory contents:"
#          ls -la
#
#      - name: Install Foundry
#        run: |
#          # Install Foundry (ignore shell detection errors)
#          curl -L https://foundry.paradigm.xyz | bash || true
#
#          # Manually add to PATH for this session
#          export PATH="$HOME/.foundry/bin:$PATH"
#
#          # Run foundryup directly from its installed location
#          if [ -f "$HOME/.foundry/bin/foundryup" ]; then
#            $HOME/.foundry/bin/foundryup
#          else
#            echo "ERROR: foundryup not found at $HOME/.foundry/bin/foundryup"
#            exit 1
#          fi
#
#      - name: Install Bun
#        run: |
#          # Install Bun (ignore shell detection errors)
#          curl -fsSL https://bun.sh/install | bash || true
#
#          # Manually add to PATH for this session
#          export PATH="$HOME/.bun/bin:$PATH"
#
#          # Verify Bun is installed
#          if [ -f "$HOME/.bun/bin/bun" ]; then
#            echo "✓ Bun installed successfully"
#            $HOME/.bun/bin/bun --version
#          else
#            echo "ERROR: bun not found at $HOME/.bun/bin/bun"
#            exit 1
#          fi
#
#      - name: Build monorepo
#        run: |
#          # Add tools to PATH
#          export PATH="$HOME/.foundry/bin:$HOME/.bun/bin:$PATH"
#
#          # Verify tools are available
#          echo "Verifying tools..."
#          which forge || echo "WARNING: forge not in PATH"
#          which bun || echo "WARNING: bun not in PATH"
#
#          # Find monorepo root by looking for package.json with workspaces
#          echo "Current directory: $(pwd)"
#          echo "Looking for monorepo root..."
#
#          # Start from current directory and search upwards for package.json with workspaces
#          MONOREPO_ROOT=$(pwd)
#          while [ "$MONOREPO_ROOT" != "/" ]; do
#            if [ -f "$MONOREPO_ROOT/package.json" ] && grep -q "workspaces" "$MONOREPO_ROOT/package.json"; then
#              echo "Found monorepo root at: $MONOREPO_ROOT"
#              break
#            fi
#            MONOREPO_ROOT=$(dirname "$MONOREPO_ROOT")
#          done
#
#          if [ "$MONOREPO_ROOT" = "/" ]; then
#            echo "ERROR: Could not find monorepo root (package.json with workspaces)"
#            exit 1
#          fi
#
#          # Navigate to monorepo root and build
#          cd "$MONOREPO_ROOT"
#          echo "Building monorepo from $(pwd)..."
#          ls -la package.json
#          yarn build
#
#      - name: Publish update
#        run: |
#          # eas update needs to run from the expo app directory
#          eas update --branch production --platform ios --non-interactive
