-- Disable default privileges for functions in the future
ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS
FROM PUBLIC;

ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS
FROM anon;

ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS
FROM authenticated;
