CREATE TABLE temporal_workflows(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workflow_id text NOT NULL,
  user_id text NOT NULL,
  user_op_hash text NOT NULL,
  workflow_type text NOT NULL,
  status text NOT NULL CHECK (status IN ('simulating', 'sending', 'waiting', 'indexing', 'confirmed')),
  data jsonb NOT NULL, -- Contains the full workflow state including userOp, hash, receipt etc
  created_at timestamp with time zone DEFAULT NOW(),
  updated_at timestamp with time zone DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX temporal_workflows_user_id_idx ON temporal_workflows(user_id);

CREATE INDEX temporal_workflows_user_op_hash_idx ON temporal_workflows(user_op_hash);

CREATE INDEX temporal_workflows_status_idx ON temporal_workflows(status);

-- Update the updated_at timestamp
CREATE TRIGGER set_timestamp
  BEFORE UPDATE ON temporal_workflows
  FOR EACH ROW
  EXECUTE PROCEDURE trigger_set_timestamp();

-- Create unique constraint on workflow_id
CREATE UNIQUE INDEX temporal_workflows_workflow_id_idx ON temporal_workflows(workflow_id);

