name: Docker Build
on:
  pull_request:
    types:
      - closed
    branches:
      - 'releases/**'
      - 'dev'
      - 'main'
jobs:
  build-docker:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build & Push Docker Image for next-app
        env:
            SUPABASE_SERVICE_ROLE: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_SUPABASE_SERVICE_ROLE || secrets.DEV_SUPABASE_SERVICE_ROLE}}
            SUPABASE_DB_URL: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_SUPABASE_DB_URL || secrets.DEV_SUPABASE_DB_URL}}
        uses: ./.github/actions/docker-build
        with:
          build-nextjs-docker: true
          push-nextjs-docker-image: true
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
