name: Docker Build
on:
  # manual trigger for now
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - 'releases/**'
  #     - 'dev'
  #     - 'main'
  workflow_dispatch:
jobs:
  build-docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    #    needs: [cache-deps]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build & Push Docker Image for next-app
        uses: ./.github/actions/docker-build
        with:
          package: next-app
          ghcr-token: ${{ secrets.GITHUB_TOKEN }}
