name: Docker Build
on:
  pull_request:
    types:
      - closed
    branches:
      - 'releases/**'
      - 'dev'
      - 'main'
jobs:
  build-docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
#    needs: [cache-deps]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build & Push Docker Image for next-app
        uses: ./.github/actions/docker-build
        with:
          build-nextjs-docker: true
          push-nextjs-docker-image: true
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
