name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          allowed_tools: >
            Bash(git status),
            Bash(git add .),
            Bash(git add *),
            Bash(git commit -m *),
            Bash(git diff),
            Bash(git diff --staged),
            Bash(git log --oneline -10),
            Bash(git branch),
            Bash(git checkout *),
            Bash(npm install),
            Bash(npm run test),
            Bash(npm run build),
            Bash(npm run lint),
            Bash(npm run format),
            Bash(yarn install),
            Bash(yarn test),
            Bash(yarn build),
            Bash(yarn lint),
            Bash(yarn format),
            Bash(npx @biomejs/biome check),
            Bash(npx @biomejs/biome format *),
            Bash(yarn supabase test),
            Bash(yarn playwright test),
            Edit,
            MultiEdit,
            Write,
            Read,
            Glob,
            Grep,
            LS,
            Task,
            TodoRead,
            TodoWrite

