name: Deploy Dev
on:
  push:
    branches: [dev]
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deployer.key
          chmod 600 ~/.ssh/deployer.key
          for h in $DEV_DOCKER_DEPLOYMENT_TARGETS; do echo Deploying to $h && \
          ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no $DEPLOYER_USERNAME@$h \
          'cd /opt/next-app-dev && docker compose pull && docker compose up -d' ; done
        env:
          SSH_USER: ${{ secrets.DEPLOYER_SSH_USER }}
          SSH_KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
          DEPLOYMENT_TARGETS: ${{ secrets.DEV_DOCKER_DEPLOYMENT_TARGETS }}
